#!/usr/bin/env python3
"""
RAGAS evaluation of the grounded estimation pipeline.

Usage:
    docker compose run --rm ai_service python scripts/evaluate_ragas.py

For each golden query this script collects the four RAGAS inputs:
    question      -> the estimation request (golden query text)
    answer        -> the grounded estimate generated by the pipeline (as text)
    contexts      -> the retrieved chunks passed to the generator
    ground_truth  -> the reference estimate from the extended golden set

Then it computes the four RAGAS metrics with an OpenAI judge + embeddings:
    faithfulness, answer_relevancy, context_precision, context_recall

Outputs: per-query table + aggregate, CSV, and JSON.
"""

import sys
import asyncio
import json
import types
from pathlib import Path

# Compatibility shim: ragas 0.2.x hard-imports
# langchain_community.chat_models.vertexai, a module removed in newer
# langchain-community. We never use Vertex AI (the judge is OpenAI), so inject a
# lightweight stub so the import succeeds without downgrading the whole stack.
try:  # pragma: no cover - environment dependent
    import langchain_community.chat_models.vertexai  # noqa: F401
except ModuleNotFoundError:
    _vertexai_stub = types.ModuleType("langchain_community.chat_models.vertexai")

    class ChatVertexAI:  # placeholder, never instantiated
        pass

    _vertexai_stub.ChatVertexAI = ChatVertexAI
    sys.modules["langchain_community.chat_models.vertexai"] = _vertexai_stub

# Add project to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from app.config import AsyncSessionLocal

JUDGE_MODEL = "gpt-4o-mini"
EMBEDDING_MODEL = "text-embedding-3-small"


def estimate_to_text(estimate) -> str:
    """Serialize a GroundedEstimateOutput into the answer text RAGAS evaluates."""
    lines = [f"Project summary: {estimate.project_summary}", "", "Line items:"]
    for item in estimate.line_items:
        if item.grounded:
            cited = ", ".join(source.chunk_id for source in item.sources)
            lines.append(
                f"- {item.component}: {item.hours}h. {item.rationale} "
                f"(sources: {cited})"
            )
        else:
            lines.append(
                f"- {item.component}: not grounded (insufficient source data). "
                f"{item.rationale}"
            )
    lines.append("")
    lines.append(f"Total hours: {estimate.total_hours}")
    return "\n".join(lines)


async def build_samples() -> list[dict]:
    """Run the grounded pipeline for each golden query and assemble RAGAS samples."""
    from embedding_pipeline.grounded_generation import GroundedEstimator
    from embedding_pipeline.persistence import DocumentRepository

    golden_set_path = project_root / "evals" / "golden_set_session_10.json"
    with open(golden_set_path, encoding="utf-8") as f:
        golden_set = json.load(f)

    samples = []

    async with AsyncSessionLocal() as session:
        repository = DocumentRepository(session)
        estimator = GroundedEstimator(repository)

        for query in golden_set["queries"]:
            query_id = query["id"]
            question = query["text"]
            ground_truth = query["ground_truth"]

            print(f"  Generating grounded estimate for {query_id}: {question[:55]}...")

            result = await estimator.generate(
                query=question,
                search_k=5,
                search_mode="semantic",
                request_id=f"ragas-{query_id}",
            )

            samples.append(
                {
                    "id": query_id,
                    "question": question,
                    "answer": estimate_to_text(result["estimate"]),
                    "contexts": result["contexts"],
                    "ground_truth": ground_truth,
                }
            )

    return samples


def run_ragas(samples: list[dict]):
    """Configure RAGAS (0.2.x) with an OpenAI judge + embeddings and compute the 4 metrics."""
    from langchain_openai import ChatOpenAI, OpenAIEmbeddings
    from ragas import EvaluationDataset, evaluate
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from ragas.llms import LangchainLLMWrapper
    from ragas.metrics import (
        Faithfulness,
        LLMContextPrecisionWithReference,
        LLMContextRecall,
        ResponseRelevancy,
    )

    evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model=JUDGE_MODEL, temperature=0))
    evaluator_embeddings = LangchainEmbeddingsWrapper(
        OpenAIEmbeddings(model=EMBEDDING_MODEL)
    )

    # RAGAS 0.2.x column names: user_input, response, retrieved_contexts, reference
    dataset = EvaluationDataset.from_list(
        [
            {
                "user_input": s["question"],
                "response": s["answer"],
                "retrieved_contexts": s["contexts"],
                "reference": s["ground_truth"],
            }
            for s in samples
        ]
    )

    metrics = [
        Faithfulness(llm=evaluator_llm),
        ResponseRelevancy(llm=evaluator_llm, embeddings=evaluator_embeddings),
        LLMContextPrecisionWithReference(llm=evaluator_llm),
        LLMContextRecall(llm=evaluator_llm),
    ]

    result = evaluate(dataset=dataset, metrics=metrics)

    return result


def main():
    print("=" * 100)
    print("RAGAS EVALUATION — Grounded Estimation Pipeline")
    print(f"Judge: {JUDGE_MODEL} | Embeddings: {EMBEDDING_MODEL}")
    print("=" * 100)

    print("\n[STEP 1] Generating grounded estimates for golden queries")
    print("-" * 100)
    samples = asyncio.run(build_samples())
    print(f"\n✓ Collected {len(samples)} samples")

    print("\n[STEP 2] Running RAGAS metrics (judge + embeddings)")
    print("-" * 100)
    result = run_ragas(samples)

    df = result.to_pandas()
    # Attach query ids for readability
    df.insert(0, "id", [s["id"] for s in samples])

    # RAGAS 0.2.x metric column names vary by metric class; derive them as the
    # numeric columns that are not the RAGAS input columns.
    input_columns = {"id", "user_input", "response", "retrieved_contexts", "reference"}
    metric_columns = [
        col
        for col in df.columns
        if col not in input_columns
        and df[col].dtype.kind in ("f", "i")
    ]

    print("\n" + "=" * 100)
    print("[STEP 3] RESULTS")
    print("=" * 100)

    print("\nPER-QUERY SCORES")
    print("-" * 100)
    header = f"{'Query':<8}" + "".join(f"{m:<32}" for m in metric_columns)
    print(header)
    print("-" * 100)
    for _, row in df.iterrows():
        line = f"{row['id']:<8}"
        for metric in metric_columns:
            value = row.get(metric)
            line += f"{value:<32.4f}" if value is not None else f"{'n/a':<32}"
        print(line)

    print("\nAGGREGATE (mean across queries)")
    print("-" * 100)
    for metric in metric_columns:
        print(f"  {metric:<40}: {df[metric].mean():.4f}")

    # Save outputs
    csv_path = project_root / "evals" / "ragas_evaluation_session_11.csv"
    json_path = project_root / "evals" / "ragas_evaluation_session_11.json"

    df.to_csv(csv_path, index=False, encoding="utf-8")

    summary = {
        "judge_model": JUDGE_MODEL,
        "embedding_model": EMBEDDING_MODEL,
        "aggregate": {
            metric: float(df[metric].mean())
            for metric in metric_columns
            if metric in df.columns
        },
        "per_query": df.to_dict(orient="records"),
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False, default=str)

    # Markdown baseline table (one row per query + an average row), with the
    # four canonical metric names regardless of RAGAS's internal column names.
    md_path = project_root / "evals" / "ragas_baseline_session_11.md"
    write_markdown_baseline(df, metric_columns, md_path)

    print(f"\n✓ Saved CSV to {csv_path}")
    print(f"✓ Saved JSON to {json_path}")
    print(f"✓ Saved baseline table to {md_path}")
    print("\n" + "=" * 100)
    print("RAGAS EVALUATION COMPLETE")
    print("=" * 100)


def write_markdown_baseline(df, metric_columns, md_path):
    """Write the generation-quality baseline as a markdown table."""
    # Map RAGAS column names to the four canonical metric names.
    canonical_order = [
        "faithfulness",
        "answer_relevancy",
        "context_precision",
        "context_recall",
    ]
    column_for = {name: None for name in canonical_order}
    for col in metric_columns:
        low = col.lower()
        if "faith" in low:
            column_for["faithfulness"] = col
        elif "relevanc" in low:
            column_for["answer_relevancy"] = col
        elif "precision" in low:
            column_for["context_precision"] = col
        elif "recall" in low:
            column_for["context_recall"] = col

    def cell(row, name):
        col = column_for[name]
        return f"{row[col]:.4f}" if col is not None else "n/a"

    lines = [
        "# RAGAS Generation-Quality Baseline (Session 11)",
        "",
        f"Judge: `{JUDGE_MODEL}` | Embeddings: `{EMBEDDING_MODEL}` | Pipeline: grounded estimation",
        "",
        "| Query | " + " | ".join(canonical_order) + " |",
        "|" + "---|" * (len(canonical_order) + 1),
    ]
    for _, row in df.iterrows():
        cells = " | ".join(cell(row, name) for name in canonical_order)
        lines.append(f"| {row['id']} | {cells} |")

    avg_cells = " | ".join(
        f"**{df[column_for[name]].mean():.4f}**" if column_for[name] else "n/a"
        for name in canonical_order
    )
    lines.append(f"| **Average** | {avg_cells} |")
    lines.append("")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
